language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install: pip install -U pytest
install: pip install -U autopep8

# command to run tests
script: py.test
